M48
; DRILL file {KiCad 9.0.0} date 2025-03-14T14:05:50+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-14T14:05:50+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X5.748Y-4.4094
T2
X5.5177Y-4.7244
X6.0177Y-4.7244
T3
X4.585Y-4.6063
X4.585Y-4.7063
M30
